package com.example.plantgrid.ui.localization

object AppLocalization {
    private val odia = mapOf(
        "app_title" to "ପ୍ଲାଣ୍ଟ-ଗ୍ରୀଡ୍ AI",
        "home" to "ମୋ ଫସଲ",
        "agri_tools" to "ଆଡଭାନ୍ସଡ୍ କୃଷି ସାଧନ",
        "market" to "ମଣ୍ଡି ଦର",
        "settings" to "ମୋ ଖାତା",
        "satellite_radar" to "ଉପଗ୍ରହ ସ୍କାନର୍ ରାଡାର୍",
        "anomaly_scan" to "ସ୍କାନ୍: ସମସ୍ୟା ଅନୁସନ୍ଧାନ",
        "radius_safe" to "୧୦୦% ସୁରକ୍ଷିତ (Safe)",
        "anomaly_alert" to "ବିପଦ: ସମସ୍ୟା ଅଛି (Alert)",
        "radius_sync" to "୫୦୦ ମିଟର ସିଙ୍କ୍",
        "climate_live" to "ଲାଇଭ୍ ପାଣିପାଗ",
        "temp" to "ତାପମାତ୍ରା",
        "wind" to "ପବନର ଗତି",
        "health_meter" to "ଗଛର ସ୍ୱାସ୍ଥ୍ୟ ମିଟର",
        "sap_flow" to "ଜଳ ପ୍ରବାହ (Sap Flow)",
        "plant_fever" to "ଗଛର ଜ୍ୱର (Temp)",
        "metabolic_eff" to "ଗଛର ଶକ୍ତି (Efficiency)",
        "health_safe_msg" to "ଆପଣଙ୍କ ଗଛ ଏକଦମ ସୁସ୍ଥ ଅଛି।",
        "health_warn_msg" to "ଗଛକୁ ଅଳ୍ପ ପାଣି ଦରକାର।",
        "precision_matrix" to "ପ୍ରିସିସନ ପ୍ରଣାଳୀ",
        "fertilizer_calc" to "ସାର କ୍ୟାଲକୁଲେଟର",
        "medicine_ai" to "ଔଷଧ ମାତ୍ରା AI",
        "crop_lib" to "ଫସଲ ଜ୍ଞାନ କୋଷ",
        "project_guide" to "ପ୍ରକଳ୍ପ ସୂଚୀ",
        "pest_disease_ai" to "ପୋକ ଓ ରୋଗ AI",
        "active_profile" to "ସକ୍ରିୟ ଫସଲ",
        "lang_select" to "ଭାଷା ଚୟନ କରନ୍ତୁ",
        "crop_select_title" to "ଫସଲ ଚୟନ",
        "medicine_matrix_title" to "ଔଷଧ ଏବଂ ଚିକିତ୍ସା ଗାଇଡ୍",
        "symptoms" to "ଲକ୍ଷଣ",
        "remedy" to "ପ୍ରତିକାର",
        "dosage" to "ମାତ୍ରା",
        "price" to "ମୂଲ୍ୟ",
        "voice_active" to "ଆପଣଙ୍କ ସ୍ୱର ଶୁଣୁଛି...",
        "account_title" to "ଆପଣଙ୍କ ଆକାଉଣ୍ଟ",
        "account_sub" to "ପ୍ଲାଣ୍ଟଗ୍ରୀଡ୍ କମ୍ୟୁନିଟିରେ ଯୋଗ ଦିଅନ୍ତୁ",
        "sign_in" to "ସାଇନ୍ ଇନ୍",
        "exp_title" to "ଆପଣଙ୍କ ଅଭିଜ୍ଞତା କିପରି ଅଛି?",
        "exp_sub" to "ଆମେ ଆପଣଙ୍କର ପରାମର୍ଶ ଶୁଣିବାକୁ ପସନ୍ଦ କରିବୁ।",
        "feedback" to "ମତାମତ ଦିଅନ୍ତୁ",
        "share_title" to "ଆମେ ମିଶି ସ୍ମାର୍ଟ ଉପାୟରେ ବଢ଼ିବା",
        "share_sub" to "ଆପ୍‌କୁ ଶେୟାର କରି ଅନ୍ୟ ଚାଷୀମାନଙ୍କୁ ସାହାଯ୍ୟ କରନ୍ତୁ।",
        "share_app" to "ପ୍ଲାଣ୍ଟଗ୍ରୀଡ୍ ଶେୟାର କରନ୍ତୁ",
        "btn_agree" to "ସମ୍ମତି ଓ ଆଗକୁ ବଢ଼ନ୍ତୁ (Continue)",
        "system_settings" to "ସିଷ୍ଟମ ସେଟିଂସ",
        "mandi_title" to "ମଣ୍ଡି ଦର",
        "loc_perm_title" to "ସ୍ଥାନ ପ୍ରବେଶକୁ ଅନୁମତି ଦିଅନ୍ତୁ",
        "loc_perm_sub" to "ଆପଣଙ୍କ ଅଞ୍ଚଳରେ ଉପଲବ୍ଧ ଥିବା ପ୍ରୋଡକ୍ଟଗୁଡ଼ିକୁ ଦେଖିବାକୁ, ଆପଣଙ୍କର ଅବସ୍ଥାନ ପ୍ରବେଶକୁ ଅନୁମତି ଦିଅନ୍ତୁ।",
        "allow_loc" to "ଅବସ୍ଥାନ ଅନୁମତି ଦିଅନ୍ତୁ",
        "org_fert" to "ଜୈବିକ ସାର",
        "reserve" to "ସଂରକ୍ଷଣ କରନ୍ତୁ",
        "comm_title" to "ପ୍ଲାଣ୍ଟଗ୍ରୀଡ୍ କମ୍ୟୁନିଟି",
        "digi_ast" to "ଡିଜିଟାଲ୍ ସହାୟକ",
        "cult_cycle" to "ଚାଷ ଚକ୍ର",
        "exp_forum" to "ବିଶେଷଜ୍ଞ ମଞ୍ଚ",
        "fin_view" to "ଆର୍ଥିକ ସମୀକ୍ଷା",
        "ask_crops" to "ଫସଲ ବିଷୟରେ ପଚାରନ୍ତୁ...",
        "ongoing" to "ଚାଲୁଅଛି",
        "earnings" to "ଆୟର ଧାରା",
        "revenue" to "ସମୁଦାୟ ରାଜସ୍ୱ",
        "expenses" to "ସମୁଦାୟ ଖର୍ଚ୍ଚ",
        "crop_paddy" to "ଧାନ (Paddy)",
        "crop_mango" to "ଆମ୍ବ (Mango)",
        "crop_potato" to "ଆଳୁ (Potato)",
        "crop_onion" to "ପିଆଜ (Onion)",
        "crop_paddy_advice" to "ଧାନ କାଣ୍ଡ ବିନ୍ଧା ପୋକ ପାଇଁ କ୍ଲୋରପାଇରିଫସ ପ୍ରୟୋଗ କରନ୍ତୁ।",
        "crop_mango_advice" to "ଆମ୍ବ ବଉଳ ସୁରକ୍ଷା ପାଇଁ କୀଟନାଶକ ପାଣି ସ୍ପ୍ରେ କରନ୍ତୁ।",
        "default_advice" to "ଜମି ସମ୍ପୂର୍ଣ୍ଣ ସୁରକ୍ଷିତ ଅଛି, ସାର ସୂଚୀ ଦେଖନ୍ତୁ।",
        "stem_borer_title" to "କାଣ୍ଡ ବିନ୍ଧା ପୋକ",
        "stem_borer_symp" to "ଗଛର କାଣ୍ଡ ଶୁଖିଯାଏ ଏବଂ ପୋକ ଖାଇଦିଏ।",
        "stem_borer_med" to "କାର୍ଟାପ୍ ହାଇଡ୍ରୋକ୍ଲୋରାଇଡ୍",
        "stem_borer_dose" to "୭.୫ କେଜି ପ୍ରତି ଏକର ମାଟିରେ ମିଶାନ୍ତୁ।",
        "leaf_blight_title" to "ପତ୍ର ପୋଡ଼ା ରୋଗ",
        "leaf_blight_symp" to "ପତ୍ରର ଧାରଗୁଡ଼ିକ ହଳଦିଆ ହୋଇ ଶୁଖିଯାଏ।",
        "leaf_blight_med" to "ଷ୍ଟ୍ରେପ୍ଟୋସାଇକ୍ଲିନ୍ + କପର",
        "leaf_blight_dose" to "୬ ଗ୍ରାମ + ୫୦୦ ଗ୍ରାମ ସ୍ପ୍ରେ କରନ୍ତୁ।",
        "cult_roadmap" to "ଆପଣଙ୍କ ଚାଷ ରୋଡମ୍ୟାପ୍",
        "step1_title" to "ମାଟି ପ୍ରସ୍ତୁତି (Soil Setup)",
        "step1_desc" to "ମାଟି ପରୀକ୍ଷା କରନ୍ତୁ ଏବଂ ଜୈବିକ ଖତ ମିଶାନ୍ତୁ।",
        "step2_title" to "ବିହନ ବିଶୋଧନ (Sowing)",
        "step2_desc" to "ଉନ୍ନତ ବିହନ ବ୍ୟବହାର କରନ୍ତୁ ଏବଂ ବିଶୋଧନ କରନ୍ତୁ।",
        "step3_title" to "ପ୍ରିସିସନ ଜଳସେଚନ (AWD)",
        "step3_desc" to "ସେନ୍ସର ଅନୁଯାୟୀ ପାଣିର ସ୍ତର ରଖନ୍ତୁ।",
        "step4_title" to "ପୋକ ଓ ପୋଷଣ ପରିଚାଳନା",
        "step4_desc" to "NPK ମାତ୍ରା ଯାଞ୍ଚ କରନ୍ତୁ ଏବଂ ସମୟରେ ସ୍ପ୍ରେ କରନ୍ତୁ।",
        "init_title" to "ଚାଷ ପ୍ରଣାଳୀ ଚୟନ କରନ୍ତୁ",
        "init_sub" to "ପ୍ଲାଣ୍ଟଗ୍ରୀଡ୍ କିପରି ଆପଣଙ୍କ ଜମିକୁ ସ୍ମାର୍ଟ କରିବ ଚୟନ କରନ୍ତୁ",
        "mode_comm_title" to "ବ୍ୟାବସାୟିକ ଅଧିକ-ଲାଭ (Commercial)",
        "mode_comm_desc" to "ମଣ୍ଡିରେ ଅଧିକ ଦର ଏବଂ ଉପଗ୍ରହ ନଜର",
        "mode_organic_title" to "ଜୈବିକ ଓ ସୁସ୍ଥ ମାଟି (Organic)",
        "mode_organic_desc" to "ମାଟିର ଶକ୍ତି ବୃଦ୍ଧି ଏବଂ କୀଟନାଶକ ମୁକ୍ତ ଚାଷ",
        "mode_yield_title" to "ସେନ୍ସର ଆଧାରିତ ଚାଷ (High-Yield)",
        "mode_yield_desc" to "IoT ସେନ୍ସର ଦ୍ୱାରା ପ୍ରତି ଏକରରେ ସର୍ବାଧିକ ଅମଳ"
    )

    private val hindi = mapOf(
        "app_title" to "प्लांट-ग्रिड AI",
        "home" to "मेरी फसल",
        "agri_tools" to "उन्नत कृषि उपकरण",
        "market" to "मंडी भाव",
        "settings" to "मेरा खाता",
        "satellite_radar" to "सैटेलाइट रडार स्कैनर",
        "anomaly_scan" to "स्कैन: समस्या की जांच",
        "radius_safe" to "100% सुरक्षित (Safe)",
        "anomaly_alert" to "खतरा: समस्या मिली (Alert)",
        "radius_sync" to "500 मीटर सिंक",
        "climate_live" to "लाइव मौसम",
        "temp" to "तापमान",
        "wind" to "हवा की गति",
        "health_meter" to "पौधों का स्वास्थ्य",
        "sap_flow" to "जल प्रवाह (Sap Flow)",
        "plant_fever" to "पौधों का बुखार (Temp)",
        "metabolic_eff" to "पौधों की शक्ति (Efficiency)",
        "health_safe_msg" to "आपका पौधा पूरी तरह स्वस्थ है।",
        "health_warn_msg" to "पौधे को थोड़े पानी की जरूरत है।",
        "precision_matrix" to "सटीक खेती प्रणाली",
        "fertilizer_calc" to "खाद कैलकुलेटर",
        "medicine_ai" to "दवा मात्रा AI",
        "crop_lib" to "फसल ज्ञान कोष",
        "project_guide" to "परियोजना गाइड",
        "pest_disease_ai" to "कीट और रोग AI",
        "active_profile" to "सक्रिय फसल",
        "lang_select" to "भाषा का चयन करें",
        "crop_select_title" to "फसल का चयन",
        "medicine_matrix_title" to "दवा और उपचार गाइड",
        "symptoms" to "लक्षण",
        "remedy" to "उपचार",
        "dosage" to "मात्रा",
        "price" to "कीमत",
        "voice_active" to "आपकी आवाज़ सुन रहे हैं...",
        "account_title" to "आपका खाता",
        "account_sub" to "प्लांटग्रिड कम्युनिटी में शामिल हों",
        "sign_in" to "साइन इन करें",
        "exp_title" to "आपका अनुभव कैसा है?",
        "exp_sub" to "हम आपके सुझाव सुनना पसंद करेंगे।",
        "feedback" to "प्रतिक्रिया दें",
        "share_title" to "आइए मिलकर स्मार्ट तरीके से बढ़ें",
        "share_sub" to "ऐप शेयर करके अन्य किसानों की मदद करें।",
        "share_app" to "प्लांटग्रिड शेयर करें",
        "btn_agree" to "सहमति दें और आगे बढ़ें (Continue)",
        "system_settings" to "सिस्टम सेटिंग्स",
        "mandi_title" to "मंडी भाव",
        "loc_perm_title" to "स्थान की अनुमति दें",
        "loc_perm_sub" to "अपने क्षेत्र में उपलब्ध उत्पादों को देखने के लिए, कृपया स्थान की अनुमति दें।",
        "allow_loc" to "स्थान की अनुमति दें",
        "org_fert" to "जैविक खाद",
        "reserve" to "आरक्षित करें",
        "comm_title" to "प्लांटग्रिड कम्युनिटी",
        "digi_ast" to "डिजिटल सहायक",
        "cult_cycle" to "खेती चक्र",
        "exp_forum" to "विशेषज्ञ मंच",
        "fin_view" to "वित्तीय समीक्षा",
        "ask_crops" to "फसलों के बारे में पूछें...",
        "ongoing" to "जारी है",
        "earnings" to "कमाई का रुझान",
        "revenue" to "कुल राजस्व",
        "expenses" to "कुल खर्च",
        "crop_paddy" to "धान (Paddy)",
        "crop_mango" to "आम (Mango)",
        "crop_potato" to "आलू (Potato)",
        "crop_onion" to "प्याज (Onion)",
        "crop_paddy_advice" to "धान के तना छेदक के लिए क्लोरपायरीफोस का प्रयोग करें।",
        "crop_mango_advice" to "आम के बौर की सुरक्षा के लिए कीटनाशक का छिड़काव करें।",
        "default_advice" to "खेत पूरी तरह सुरक्षित है, खाद सूची देखें।",
        "stem_borer_title" to "तने का छेदक कीट",
        "stem_borer_symp" to "पौधे का तना सूख जाता है और अंदर से कीट खा जाता है।",
        "stem_borer_med" to "कार्टाप हाइड्रोक्लोराइड 4G",
        "stem_borer_dose" to "7.5 किलोग्राम प्रति एकड़ मिट्टी में मिलाएं।",
        "leaf_blight_title" to "जीवाणु झुलसा रोग",
        "leaf_blight_symp" to "पत्तियों के किनारे पीले होकर सूखने लगते हैं।",
        "leaf_blight_med" to "स्ट्रैप्टोसाइक्लिन + कॉपर",
        "leaf_blight_dose" to "6 ग्राम + 500 ग्राम स्प्रे करें।",
        "cult_roadmap" to "आपका कृषि मार्ग (Roadmap)",
        "step1_title" to "मिट्टी की तैयारी (Soil Setup)",
        "step1_desc" to "मिट्टी की जांच करें और जैविक खाद मिलाएं।",
        "step2_title" to "बुवाई और बीज उपचार (Sowing)",
        "step2_desc" to "उन्नत बीजों का उपयोग करें और उपचारित करें।",
        "step3_title" to "सटीक सिंचाई (AWD)",
        "step3_desc" to "सेंसर के अनुसार पानी का स्तर बनाए रखें।",
        "step4_title" to "कीट और पोषण प्रबंधन",
        "step4_desc" to "समय पर छिड़काव और पोषण प्रबंधन करें।",
        "init_title" to "खेती का प्रकार चुनें",
        "init_sub" to "चुनें कि प्लांटग्रिड आपकी फसल को कैसे बेहतर बनाए",
        "mode_comm_title" to "व्यावसायिक उच्च-लाभ (Commercial)",
        "mode_comm_desc" to "मंडी में अधिकतम लाभ और सैटेलाइट ट्रैकिंग",
        "mode_organic_title" to "जैविक एवं पर्यावरण-अनुकूल (Organic)",
        "mode_organic_desc" to "मिट्टी की उर्वरता और रसायन-मुक्त खेती",
        "mode_yield_title" to "हाई-टेक सेंसर तकनीक (High-Yield)",
        "mode_yield_desc" to "IoT सेंसर तकनीक से प्रति एकड़ अधिकतम उपज"
    )

    private val punjabi = mapOf(
        "app_title" to "ਪਲਾਂਟ-ਗ੍ਰਿਡ AI",
        "home" to "ਮੇਰੀ ਫਸਲ",
        "agri_tools" to "ਉੱਨਤ ਖੇਤੀ ਸੰਦ",
        "market" to "ਮੰਡੀ ਭਾਅ",
        "settings" to "ਮੇਰਾ ਖਾਤਾ",
        "satellite_radar" to "ਸੈਟੇਲਾਈਟ ਰਡਾਰ ਸਕੈਨਰ",
        "anomaly_scan" to "ਸਕੈਨ: ਸਮੱਸਿਆ ਦੀ ਜਾਂਚ",
        "radius_safe" to "100% ਸੁਰੱਖਿਅਤ (Safe)",
        "anomaly_alert" to "ਖਤਰਾ: ਸਮੱਸਿਆ ਮਿਲੀ (Alert)",
        "radius_sync" to "500 ਮੀਟਰ ਸਿੰਕ",
        "climate_live" to "ਲਾਈਵ ਮੌਸਮ",
        "temp" to "ਤਾਪਮਾਨ",
        "wind" to "ਹਵਾ ਦੀ ਗਤੀ",
        "health_meter" to "ਪੌਦਿਆਂ ਦੀ ਸਿਹਤ",
        "sap_flow" to "ਪਾਣੀ ਦਾ ਪ੍ਰਵਾਹ",
        "plant_fever" to "ਪੌਦਿਆਂ ਦਾ ਬੁਖਾਰ",
        "metabolic_eff" to "ਮੈਟਾਬੋਲਿਕ ਕੁਸ਼ਲਤਾ",
        "health_safe_msg" to "ਤੁਹਾਡੀ ਫਸਲ ਬਿਲਕੁਲ ਸਿਹਤਮੰਦ ਹੈ।",
        "health_warn_msg" to "ਪੌਦਿਆਂ ਨੂੰ ਪਾਣੀ ਦੀ ਲੋੜ ਹੈ।",
        "precision_matrix" to "ਸਟੀਕ ਖੇਤੀ ਪ੍ਰਣਾਲੀ",
        "fertilizer_calc" to "ਖਾਦ ਕੈਲਕੁਲੇਟਰ",
        "medicine_ai" to "ਦਵਾਈ ਦੀ ਮਾਤਰਾ AI",
        "crop_lib" to "ਫਸਲ ਗਿਆਨ ਕੋਸ਼",
        "project_guide" to "ਪ੍ਰੋਜੈਕਟ ਗਾਈਡ",
        "pest_disease_ai" to "ਕੀੜੇ ਅਤੇ ਰੋਗ AI",
        "active_profile" to "ਸਰਗਰਮ ਫਸਲ",
        "lang_select" to "ਭਾਸ਼ਾ ਚੁਣੋ",
        "crop_select_title" to "ਫਸਲ ਦੀ ਚੋਣ",
        "medicine_matrix_title" to "ਦਵਾਈ ਅਤੇ ਇਲਾਜ ਗਾਈਡ",
        "symptoms" to "ਲੱਛਣ",
        "remedy" to "ਇਲਾਜ",
        "dosage" to "ਮਾਤਰਾ",
        "price" to "ਕੀਮਤ",
        "voice_active" to "ਤੁਹਾਡੀ ਆਵਾਜ਼ ਸੁਣ ਰਿਹਾ ਹਾਂ...",
        "account_title" to "ਤੁਹਾਡਾ ਖਾਤਾ",
        "account_sub" to "ਪਲਾਂਟਗ੍ਰਿਡ ਕਮਿਊਨਿਟੀ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ",
        "sign_in" to "ਸਾਈਨ ਇਨ ਕਰੋ",
        "exp_title" to "ਤੁਹਾਡਾ ਅਨੁਭਵ ਕਿਵੇਂ ਹੈ?",
        "exp_sub" to "ਅਸੀਂ ਤੁਹਾਡੇ ਸੁਝਾਅ ਸੁਣਨਾ ਪਸੰਦ ਕਰਾਂਗੇ।",
        "feedback" to "ਫੀਡਬੈਕ ਦਿਓ",
        "share_title" to "ਆਓ ਮਿਲ ਕੇ ਸਮਾਰਟ ਤਰੀਕੇ ਨਾਲ ਵਧੀਏ",
        "share_sub" to "ਐਪ ਸ਼ੇਅਰ ਕਰਕੇ ਹੋਰ ਕਿਸਾਨਾਂ ਦੀ ਮਦਦ ਕਰੋ।",
        "share_app" to "ਪਲਾਂਟਗ੍ਰਿਡ ਸ਼ੇਅਰ ਕਰੋ",
        "btn_agree" to "ਸਹਿਮਤ ਹੋਵੋ ਅਤੇ ਅੱਗੇ ਵਧੋ (Continue)",
        "system_settings" to "ਸਿਸਟਮ ਸੈਟਿੰਗਜ਼",
        "mandi_title" to "ਮੰਡੀ ਭਾਅ",
        "loc_perm_title" to "ਟਿਕਾਣਾ ਪਹੁੰਚ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ",
        "loc_perm_sub" to "ਆਪਣੇ ਖੇਤਰ ਵਿੱਚ ਉਪਲਬਧ ਉਤਪਾਦਾਂ ਨੂੰ ਦੇਖਣ ਲਈ ਟਿਕਾਣਾ ਪਹੁੰਚ ਦਿਓ।",
        "allow_loc" to "ਇਜਾਜ਼ਤ ਦਿਓ",
        "org_fert" to "ਜੈਵਿਕ ਖਾਦ",
        "reserve" to "ਰਾਖਵਾਂ ਕਰੋ",
        "comm_title" to "ਪਲਾਂਟਗ੍ਰਿਡ ਕਮਿਊਨਿਟੀ",
        "digi_ast" to "ਡਿਜੀਟਲ ਸਹਾਇਕ",
        "cult_cycle" to "ਖੇਤੀ ਚੱਕਰ",
        "exp_forum" to "ਮਾਹਿਰ ਫੋਰਮ",
        "fin_view" to "ਵਿੱਤੀ ਸਮੀਖਿਆ",
        "ask_crops" to "ਫਸਲਾਂ ਬਾਰੇ ਪੁੱਛੋ...",
        "ongoing" to "ਜਾਰੀ ਹੈ",
        "earnings" to "ਕਮਾਈ ਦਾ ਰੁਝਾਨ",
        "revenue" to "ਕੁੱਲ ਆਮਦਨ",
        "expenses" to "ਕੁੱਲ ਖਰਚੇ",
        "crop_paddy" to "ਝੋਨਾ (Paddy)",
        "crop_mango" to "ਅੰਬ (Mango)",
        "crop_potato" to "ਆਲੂ (Potato)",
        "crop_onion" to "ਪਿਆਜ਼ (Onion)",
        "crop_paddy_advice" to "ਝੋਨੇ ਦੇ ਤਣੇ ਦੇ ਕੀੜੇ ਲਈ ਕਾਰਟੈਪ ਦੀ ਵਰਤੋਂ ਕਰੋ।",
        "crop_mango_advice" to "ਅੰਬ ਦੇ ਬੂਰ ਦੀ ਸੁਰੱਖਿਆ ਲਈ ਬਾਇਓ-ਫੰਗੀਸਾਈਡ ਸਪਰੇਅ ਕਰੋ।",
        "default_advice" to "ਖੇਤ ਪੂਰੀ ਤਰ੍ਹਾਂ ਸੁਰੱਖਿਅਤ ਹੈ।",
        "stem_borer_title" to "ਤਣੇ ਦਾ ਕੀੜਾ",
        "stem_borer_symp" to "ਤਣਾ ਸੁੱਕਣਾ ਅਤੇ ਅੰਦਰੂਨੀ ਨੁਕਸਾਨ।",
        "stem_borer_med" to "ਕਾਰਟੈਪ ਹਾਈਡ੍ਰੋਕਲੋਰਾਈਡ",
        "stem_borer_dose" to "7.5 ਕਿਲੋ ਪ੍ਰਤੀ ਏਕੜ।",
        "leaf_blight_title" to "ਪੱਤਾ ਝੁਲਸ ਰੋਗ",
        "leaf_blight_symp" to "ਪੱਤਿਆਂ ਦੇ ਕਿਨਾਰੇ ਪੀਲੇ ਹੋ ਕੇ ਸੁੱਕਣਾ।",
        "leaf_blight_med" to "ਸਟ੍ਰੈਪਟੋਸਾਈਕਲੀਨ + ਕਾਪਰ",
        "leaf_blight_dose" to "6 ਗ੍ਰਾਮ + 500 ਗ੍ਰਾਮ ਸਪਰੇਅ ਕਰੋ।",
        "cult_roadmap" to "ਤੁਹਾਡਾ ਖੇਤੀ ਰੋਡਮੈਪ",
        "step1_title" to "ਮਿੱਟੀ ਦੀ ਤਿਆਰੀ",
        "step1_desc" to "ਮਿੱਟੀ ਦੀ ਜਾਂਚ ਕਰੋ ਅਤੇ ਖਾਦ ਮਿਲਾਓ।",
        "step2_title" to "ਬਿਜਾਈ ਅਤੇ ਬੀਜ ਇਲਾਜ",
        "step2_desc" to "ਪ੍ਰਮਾਣਿਤ ਬੀਜ ਅਤੇ ਉਪਚਾਰ ਵਰਤੋ।",
        "step3_title" to "ਸਟੀਕ ਸਿੰਚਾਈ (AWD)",
        "step3_desc" to "ਸੈਂਸਰ ਮੁਤਾਬਕ ਪਾਣੀ ਦਾ ਪੱਧਰ ਰੱਖੋ।",
        "step4_title" to "ਕੀੜੇ ਅਤੇ ਪੋਸ਼ਣ ਪ੍ਰਬੰਧਨ",
        "step4_desc" to "ਸਮੇਂ ਸਿਰ ਨਿਗਰਾਨੀ ਅਤੇ ਇਲਾਜ।",
        "init_title" to "ਖੇਤੀ ਦਾ ਤਰੀਕਾ ਚੁਣੋ",
        "init_sub" to "ਚੁਣੋ ਕਿ ਪਲਾਂਟਗ੍ਰਿਡ ਤੁਹਾਡੀ ਖੇਤੀ ਨੂੰ ਕਿਵੇਂ ਬਿਹਤਰ ਬਣਾਵੇ",
        "mode_comm_title" to "ਵਪਾਰਕ ਵੱਧ-ਲਾਭ (Commercial)",
        "mode_comm_desc" to "ਮੰਡੀ ਵਿੱਚ ਵੱਧ ਮੁਨਾਫਾ ਅਤੇ ਸੈਟੇਲਾਈਟ ਨਿਗਰਾਨੀ",
        "mode_organic_title" to "ਜੈਵਿਕ ਖੇਤੀ (Organic)",
        "mode_organic_desc" to "ਜ਼ਮੀਨ ਦੀ ਸਿਹਤ ਅਤੇ ਰਸਾਇਣ-ਮੁਕਤ ਖੇਤੀ",
        "mode_yield_title" to "ਹਾਈ-ਟੈਕ ਸੈਂਸਰ ਤਕਨਾਲੋਜੀ",
        "mode_yield_desc" to "IoT ਸੈਂਸਰ ਨਾਲ ਪ੍ਰਤੀ ਏਕੜ ਵੱਧ ਤੋਂ ਵੱਧ ਝਾੜ"
    )

    private val urdu = mapOf(
        "app_title" to "پلانٹ-گرڈ AI",
        "home" to "میری فصل",
        "agri_tools" to "جدید زرعی آلات",
        "market" to "منڈی کے نرخ",
        "settings" to "میرا اکاؤنٹ",
        "satellite_radar" to "سیٹلائٹ ریڈار اسکینر",
        "anomaly_scan" to "اسکین: مسائل کی تلاش",
        "radius_safe" to "100% محفوظ (Safe)",
        "anomaly_alert" to "خطرہ: مسئلہ ملا (Alert)",
        "radius_sync" to "500 میٹر سنک",
        "climate_live" to "لائیو موسم",
        "temp" to "درجہ حرارت",
        "wind" to "ہوا کی رفتار",
        "health_meter" to "پودوں کی صحت",
        "sap_flow" to "پانی کا بہاؤ",
        "plant_fever" to "پودوں کا بخار",
        "metabolic_eff" to "میٹابولک کارکردگی",
        "health_safe_msg" to "آپ کی فصل بالکل صحت مند ہے۔",
        "health_warn_msg" to "پودوں کو پانی کی ضرورت ہے۔",
        "precision_matrix" to "درست زراعت کا نظام",
        "fertilizer_calc" to "کھاد کیلکولیٹر",
        "medicine_ai" to "ادویات کی مقدار AI",
        "crop_lib" to "فصلوں کا معلوماتی ذخیرہ",
        "project_guide" to "پروجیکٹ گائیڈ",
        "pest_disease_ai" to "کیڑے اور بیماریاں AI",
        "active_profile" to "فعال فصل",
        "lang_select" to "زبان منتخب کریں",
        "crop_select_title" to "فصل کا انتخاب",
        "medicine_matrix_title" to "ادویات اور علاج کی گائیڈ",
        "symptoms" to "علامات",
        "remedy" to "علاج",
        "dosage" to "مقدار",
        "price" to "قیمت",
        "voice_active" to "آپ کی آواز سن رہا ہوں...",
        "account_title" to "آپ کا اکاؤنٹ",
        "account_sub" to "پلانٹ گرڈ کمیونٹی میں شامل ہوں",
        "sign_in" to "سائن ان کریں",
        "exp_title" to "آپ کا تجربہ کیسا ہے؟",
        "exp_sub" to "ہم آپ کی تجاویز سننا پسند کریں گے۔",
        "feedback" to "رائے دیں",
        "share_title" to "آئیے مل کر اسمارٹ طریقے سے بڑھیں",
        "share_sub" to "ایپ شیئر کر کے دوسرے کسانوں کی مدد کریں۔",
        "share_app" to "پلانٹ گرڈ شیئر کریں",
        "btn_agree" to "متفق ہوں اور آگے بڑھیں (Continue)",
        "system_settings" to "سسٹم کی ترتیبات",
        "mandi_title" to "منڈی کے نرخ",
        "loc_perm_title" to "مقام تک رسائی کی اجازت دیں",
        "loc_perm_sub" to "اپنے علاقے میں دستیاب مصنوعات دیکھنے کے لیے مقام کی اجازت دیں۔",
        "allow_loc" to "اجازت دیں",
        "org_fert" to "نامیاتی کھاد",
        "reserve" to "محفوظ کریں",
        "comm_title" to "پلانٹ گرڈ کمیونٹی",
        "digi_ast" to "ڈیجیٹل اسسٹنٹ",
        "cult_cycle" to "کاشتکاری کا چکر",
        "exp_forum" to "ماہرین کا فورم",
        "fin_view" to "مالی جائزہ",
        "ask_crops" to "فصلوں کے بارے میں پوچھیں...",
        "ongoing" to "جاری ہے",
        "earnings" to "آمدنی کا رجحان",
        "revenue" to "کل آمدنی",
        "expenses" to "کل اخراجات",
        "crop_paddy" to "دھان (Paddy)",
        "crop_mango" to "آم (Mango)",
        "crop_potato" to "آلو (Potato)",
        "crop_onion" to "پیاز (Onion)",
        "crop_paddy_advice" to "دھان کے تنے کے کیڑے کے لیے کارٹاپ استعمال کریں۔",
        "crop_mango_advice" to "آم کے بور کی حفاظت کے لیے بائیو فنگسائڈ اسپرے کریں۔",
        "default_advice" to "کھیت بالکل محفوظ ہے۔",
        "stem_borer_title" to "تنے کا کیڑا",
        "stem_borer_symp" to "تنے کا خشک ہونا اور اندرونی نقصان۔",
        "stem_borer_med" to "کارٹاپ ہائیڈرو کلورائیڈ",
        "stem_borer_dose" to "7.5 کلو فی ایکڑ۔",
        "leaf_blight_title" to "پتوں کا جھلساؤ",
        "leaf_blight_symp" to "پتوں کے کناروں کا پیلا ہونا اور خشک ہونا۔",
        "leaf_blight_med" to "سٹریپٹومائسن + کاپر",
        "leaf_blight_dose" to "6 گرام + 500 گرام اسپرے کریں۔",
        "cult_roadmap" to "آپ کا زرعی روڈ میپ",
        "step1_title" to "مٹی کی تیاری",
        "step1_desc" to "مٹی کا معائنہ کریں اور کھاد شامل کریں۔",
        "step2_title" to "بوائی اور بیج کا علاج",
        "step2_desc" to "تصدیق شدہ بیج اور علاج استعمال کریں۔",
        "step3_title" to "درست آبپاشی (AWD)",
        "step3_desc" to "سینسر کے مطابق پانی کا لیول رکھیں۔",
        "step4_title" to "کیڑے اور غذائیت کا انتظام",
        "step4_desc" to "بروقت نگرانی اور علاج کریں۔",
        "init_title" to "کاشتکاری کا طریقہ منتخب کریں",
        "init_sub" to "منتخب کریں کہ پلانٹ گرڈ آپ کے کھیت کو کیسے بہتر بنائے",
        "mode_comm_title" to "تجارتی زیادہ منافع (Commercial)",
        "mode_comm_desc" to "منڈی میں زیادہ منافع اور سیٹلائٹ نگرانی",
        "mode_organic_title" to "نامیاتی زراعت (Organic)",
        "mode_organic_desc" to "مٹی کی زرخیزی اور کیمیائی ادویات سے پاک فصل",
        "mode_yield_title" to "ہائی ٹیک سینسر ٹیکنالوجی",
        "mode_yield_desc" to "IoT سینسر سے فی ایکڑ زیادہ سے زیادہ پیداوار"
    )

    private val telugu = mapOf(
        "app_title" to "ప్లాంట్-గ్రిడ్ AI",
        "home" to "నా పంటలు",
        "agri_tools" to "అధునాతన వ్యవసాయ సాధనాలు",
        "market" to "మార్కెట్ ధరలు",
        "settings" to "నా ఖాతా",
        "satellite_radar" to "శాటిలైట్ రాడార్ స్కానర్",
        "anomaly_scan" to "స్కాన్: సమస్యల గుర్తింపు",
        "radius_safe" to "100% సురక్షితం (Safe)",
        "anomaly_alert" to "ప్రమాదం: సమస్య ఉంది (Alert)",
        "radius_sync" to "500 మీటర్ల సింక్",
        "climate_live" to "లైవ్ వాతావరణం",
        "temp" to "ఉష్ణోగ్రత",
        "wind" to "గాలి వేగం",
        "health_meter" to "మొక్కల ఆరోగ్య మీటర్",
        "sap_flow" to "నీటి ప్రవాహం",
        "plant_fever" to "మొక్కల జ్వరం",
        "metabolic_eff" to "జీవక్రియ సామర్థ్యం",
        "health_safe_msg" to "మీ పంట చాలా ఆరోగ్యంగా ఉంది.",
        "health_warn_msg" to "మొక్కలకు నీరు అవసరం.",
        "precision_matrix" to "ఖచ్చితమైన వ్యవసాయ వ్యవస్థ",
        "fertilizer_calc" to "ఎరువుల కాలిక్యులేటర్",
        "medicine_ai" to "మందు మోతాదు AI",
        "crop_lib" to "పంట జ్ఞాన కోశం",
        "project_guide" to "ప్రాజెక్ట్ గైడ్",
        "pest_disease_ai" to "కీటకాలు & వ్యాధులు AI",
        "active_profile" to "ప్రస్తుత పంట",
        "lang_select" to "భాషను ఎంచుకోండి",
        "crop_select_title" to "పంట ఎంపిక",
        "medicine_matrix_title" to "మందులు & చికిత్స గైడ్",
        "symptoms" to "లక్షణాలు",
        "remedy" to "నివారణ",
        "dosage" to "మోతాదు",
        "price" to "ధర",
        "voice_active" to "మీ గొంతు వింటున్నాను...",
        "account_title" to "మీ ఖాతా",
        "account_sub" to "ప్లాంట్ గ్రిడ్ కమ్యూనిటీలో చేరండి",
        "sign_in" to "సైన్ ఇన్ చేయండి",
        "btn_agree" to "అంగీకరించి కొనసాగండి (Continue)",
        "exp_title" to "మీ అనుభవం ఎలా ఉంది?",
        "exp_sub" to "మేము మీ సలహాలను వినాలనుకుంటున్నాము.",
        "feedback" to "అభిప్రాయం ఇవ్వండి",
        "share_title" to "కలిసి స్మార్ట్‌గా ఎదుగుదాం",
        "share_sub" to "యాప్‌ని షేర్ చేయడం ద్వారా ఇతర రైతులకు సహాయం చేయండి.",
        "share_app" to "ప్లాంట్ గ్రిడ్ షేర్ చేయండి",
        "system_settings" to "సిస్టమ్ సెట్టింగ్‌లు",
        "mandi_title" to "మార్కెట్ ధరలు",
        "loc_perm_title" to "స్థాన ప్రాప్తిని అనుమతించండి",
        "loc_perm_sub" to "మీ ప్రాంతంలో అందుబాటులో ఉన్న ఉత్పత్తులను చూడటానికి స్థాన అనుమతి ఇవ్వండి.",
        "allow_loc" to "అనుమతించు",
        "org_fert" to "సేంద్రీయ ఎరువు",
        "reserve" to "రిజర్వ్ చేయండి",
        "comm_title" to "ప్లాంట్ గ్రిడ్ కమ్యూనిటీ",
        "digi_ast" to "డిజిటల్ అసిస్టెంట్",
        "cult_cycle" to "సాగు చక్రం",
        "exp_forum" to "నిపుణుల ఫోరమ్",
        "fin_view" to "ఆర్థిక సమీక్ష",
        "ask_crops" to "పంటల గురించి అడగండి...",
        "ongoing" to "కొనసాగుతోంది",
        "earnings" to "ఆదాయ ధోరణి",
        "revenue" to "మొత్తం ఆదాయం",
        "expenses" to "మొత్తం ఖర్చులు",
        "crop_paddy" to "వరి (Paddy)",
        "crop_mango" to "మామిడి (Mango)",
        "crop_potato" to "బంగాళదుంప (Potato)",
        "crop_onion" to "ఉల్లిపాయ (Onion)",
        "crop_paddy_advice" to "వరి కాండం తొలిచే పురుగు కోసం కార్టాప్ వాడండి.",
        "crop_mango_advice" to "మామిడి పూత రక్షణ కోసం బయో-ఫంగిసైడ్ స్ప్రే చేయండి.",
        "default_advice" to "పొలం సురక్షితంగా ఉంది.",
        "stem_borer_title" to "కాండం తొలిచే పురుగు",
        "stem_borer_symp" to "కాండం ఎండిపోవడం మరియు నష్టం.",
        "stem_borer_med" to "కార్టాప్ హైడ్రోక్లోరైడ్",
        "stem_borer_dose" to "ఎకరాకు 7.5 కేజీలు.",
        "leaf_blight_title" to "ఆకు ఎండు తెగులు",
        "leaf_blight_symp" to "ఆకు అంచులు పసుపు రంగులోకి మారి ఎండిపోవడం.",
        "leaf_blight_med" to "స్ట్రెప్టోసైక్లిన్ + కాపర్",
        "leaf_blight_dose" to "6 గ్రా + 500 గ్రా స్ప్రే చేయండి.",
        "cult_roadmap" to "మీ సాగు రోడ్ మ్యాప్",
        "step1_title" to "నేల తయారీ",
        "step1_desc" to "నేల పరీక్ష చేయండి మరియు ఎరువులు కలపండి.",
        "step2_title" to "విత్తన శుద్ధి & విత్తడం",
        "step2_desc" to "ధృవీకరించబడిన విత్తనాలు మరియు శుద్ధి వాడండి.",
        "step3_title" to "ఖచ్చితమైన నీటి పారుదల (AWD)",
        "step3_desc" to "సెన్సార్ ప్రకారం నీటి మట్టం ఉంచండి.",
        "step4_title" to "కీటకాలు & పోషణ నిర్వహణ",
        "step4_desc" to "సకాలంలో పర్యవేక్షణ మరియు చికిత్స.",
        "init_title" to "సాగు విధానాన్ని ఎంచుకోండి",
        "init_sub" to "ప్లాంట్ గ్రిడ్ మీ పొలాన్ని ఎలా మెరుగుపరచాలో ఎంచుకోండి",
        "mode_comm_title" to "వాణిజ్య అధిక-లాభం (Commercial)",
        "mode_comm_desc" to "మార్కెట్‌లో గరిష్ట లాభం మరియు శాటిలైట్ పర్యవేక్షణ",
        "mode_organic_title" to "సేంద్రీయ సాగు (Organic)",
        "mode_organic_desc" to "నేల ఆరోగ్యం మరియు రసాయన రహిత పంటలు",
        "mode_yield_title" to "హై-టెక్ సెన్సార్ సాంకేతికత",
        "mode_yield_desc" to "IoT సెన్సార్లతో ఎకరాకు గరిష్ట దిగుబడి"
    )

    private val bengali = mapOf(
        "app_title" to "প্ল্যান্ট-গ্রিড AI",
        "home" to "আমার ফসল",
        "agri_tools" to "উন্নত কৃষি সরঞ্জাম",
        "market" to "মন্ডি দর",
        "settings" to "আমার অ্যাকাউন্ট",
        "satellite_radar" to "স্যাটেলাইট রাডার স্ক্যানার",
        "anomaly_scan" to "স্ক্যান: সমস্যা শনাক্তকরণ",
        "radius_safe" to "১০০% সুরক্ষিত (Safe)",
        "anomaly_alert" to "বিপদ: সমস্যা পাওয়া গেছে (Alert)",
        "radius_sync" to "৫০০ মিটার সিঙ্ক",
        "climate_live" to "লাইভ আবহাওয়া",
        "temp" to "তাপমাত্রা",
        "wind" to "বাতাসের গতি",
        "health_meter" to "গাছের স্বাস্থ্য মিটার",
        "sap_flow" to "জল প্রবাহ",
        "plant_fever" to "গাছের জ্বর (Temp)",
        "metabolic_eff" to "বিপাকীয় দক্ষতা",
        "health_safe_msg" to "আপনার গাছ একদম সুস্থ আছে।",
        "health_warn_msg" to "গাছে জলের প্রয়োজন আছে।",
        "precision_matrix" to "সঠিক কৃষি পদ্ধতি",
        "fertilizer_calc" to "সার ক্যালকুলেটর",
        "medicine_ai" to "ওষুধের মাত্রা AI",
        "crop_lib" to "ফসল জ্ঞান ভাণ্ডার",
        "project_guide" to "প্রকল্প নির্দেশিকা",
        "pest_disease_ai" to "কীটপতঙ্গ ও রোগ AI",
        "active_profile" to "সক্রিয় ফসল",
        "lang_select" to "ভাষা নির্বাচন করুন",
        "crop_select_title" to "ফসল নির্বাচন",
        "medicine_matrix_title" to "ওষুধ ও চিকিৎসা গাইড",
        "symptoms" to "লক্ষণ",
        "remedy" to "প্রতিকার",
        "dosage" to "মাত্রা",
        "price" to "মূল্য",
        "voice_active" to "আপনার কথা শুনছি...",
        "account_title" to "আপনার অ্যাকাউন্ট",
        "account_sub" to "প্ল্যান্ট গ্রিড কমিউনিটিতে যোগ দিন",
        "sign_in" to "সাইন ইন করুন",
        "btn_agree" to "সম্মতি দিন ও এগিয়ে যান (Continue)",
        "exp_title" to "আপনার অভিজ্ঞতা কেমন?",
        "exp_sub" to "আমরা আপনার পরামর্শ শুনতে চাই।",
        "feedback" to "মতামত দিন",
        "share_title" to "আসুন একসাথে স্মার্টভাবে বড় হই",
        "share_sub" to "অ্যাপটি শেয়ার করে অন্য কৃষকদের সাহায্য করুন।",
        "share_app" to "প্ল্যান্ট গ্রিড শেয়ার করুন",
        "system_settings" to "সিস্টেম সেটিংস",
        "mandi_title" to "মন্ডি দর",
        "loc_perm_title" to "লোকেশন অ্যাক্সেসের অনুমতি দিন",
        "loc_perm_sub" to "আপনার এলাকায় উপলব্ধ পণ্যগুলি দেখতে লোকেশন অনুমতি দিন।",
        "allow_loc" to "অনুমতি দিন",
        "org_fert" to "জৈব সার",
        "reserve" to "রিজার্ভ করুন",
        "comm_title" to "প্ল্যান্ট গ্রিড কমিউনিটি",
        "digi_ast" to "ডিজিটাল সহকারী",
        "cult_cycle" to "চাষের চক্র",
        "exp_forum" to "বিশেষজ্ঞ ফোরাম",
        "fin_view" to "আর্থিক পর্যালোচনা",
        "ask_crops" to "ফসল সম্পর্কে জিজ্ঞাসা করুন...",
        "ongoing" to "চলছে",
        "earnings" to "আয়ের ধারা",
        "revenue" to "মোট রাজস্ব",
        "expenses" to "মোট খরচ",
        "crop_paddy" to "ধান (Paddy)",
        "crop_mango" to "আম (Mango)",
        "crop_potato" to "আলু (Potato)",
        "crop_onion" to "পিঁয়াজ (Onion)",
        "crop_paddy_advice" to "ধানের মাজরা পোকার জন্য কারটাপ ব্যবহার করুন।",
        "crop_mango_advice" to "আমের মুকুল রক্ষার জন্য বায়ো-ফাঙ্গিসাইড স্প্রে করুন।",
        "default_advice" to "জমি একদম সুরক্ষিত আছে।",
        "stem_borer_title" to "মাজরা পোকা",
        "stem_borer_symp" to "গাছের কাণ্ড শুকিয়ে যাওয়া এবং পোকা খাওয়া।",
        "stem_borer_med" to "কারটাপ হাইড্রোক্লোরাইড",
        "stem_borer_dose" to "একর প্রতি ৭.৫ কেজি।",
        "leaf_blight_title" to "পাতা পোড়া রোগ",
        "leaf_blight_symp" to "পাতার ধার হলুদ হয়ে শুকিয়ে যাওয়া।",
        "leaf_blight_med" to "স্ট্রেপটোসাইক্লিন + কপার",
        "leaf_blight_dose" to "৬ গ্রাম + ৫০০ গ্রাম স্প্রে করুন।",
        "cult_roadmap" to "আপনার চাষের রোডম্যাপ",
        "step1_title" to "জমি প্রস্তুতি",
        "step1_desc" to "মাটি পরীক্ষা করুন এবং সার মেশান।",
        "step2_title" to "বীজ শোধন ও বপন",
        "step2_desc" to "উন্নত বীজ এবং শোধন ব্যবহার করুন।",
        "step3_title" to "সঠিক সেচ (AWD)",
        "step3_desc" to "সেন্সর অনুযায়ী জলের স্তর বজায় রাখুন।",
        "step4_title" to "পোকা ও পুষ্টি ব্যবস্থাপনা",
        "step4_desc" to "সময়মতো পর্যবেক্ষণ ও প্রতিকার।",
        "init_title" to "চাষের পদ্ধতি নির্বাচন করুন",
        "init_sub" to "প্ল্যান্ট গ্রিড কীভাবে আপনার জমি উন্নত করবে তা বেছে নিন",
        "mode_comm_title" to "বাণিজ্যিক উচ্চ-লাভ (Commercial)",
        "mode_comm_desc" to "মন্ডিতে সর্বাধিক লাভ ও স্যাটেলাইট পর্যবেক্ষণ",
        "mode_organic_title" to "জৈব চাষ (Organic)",
        "mode_organic_desc" to "মাটির উর্বরতা ও রাসায়নিক মুক্ত ফসল",
        "mode_yield_title" to "হাই-টেক সেন্সর প্রযুক্তি",
        "mode_yield_desc" to "IoT সেন্সর প্রযুক্তির মাধ্যমে একর প্রতি সর্বোচ্চ ফলন"
    )

    private val english = mapOf(
        "app_title" to "PlantGrid AI",
        "home" to "My Crops",
        "agri_tools" to "Advanced Agri-Tools",
        "market" to "Mandi Rates",
        "settings" to "My Account",
        "satellite_radar" to "Satellite Radar Scanner",
        "anomaly_scan" to "Scan: Anomaly Detection",
        "radius_safe" to "100% Safe Bounds",
        "anomaly_alert" to "Danger: Anomaly Alert",
        "radius_sync" to "500m Radius Sync",
        "climate_live" to "Live Micro-Climate",
        "temp" to "Temperature",
        "wind" to "Wind Speed",
        "health_meter" to "Plant Health Meter",
        "sap_flow" to "Water Intake (Sap Flow)",
        "plant_fever" to "Plant Fever Index",
        "metabolic_eff" to "Metabolic Efficiency",
        "health_safe_msg" to "Your crops are in optimal condition.",
        "health_warn_msg" to "Crops need hydration attention.",
        "precision_matrix" to "Precision Systems",
        "fertilizer_calc" to "Fertilizer Calculator",
        "medicine_ai" to "Medicine Dosage AI",
        "crop_lib" to "Crop Knowledge Base",
        "project_guide" to "Project Guide",
        "pest_disease_ai" to "Pest & Disease AI",
        "active_profile" to "Active Profile",
        "lang_select" to "Select Language",
        "crop_select_title" to "Select Crop",
        "medicine_matrix_title" to "Remedy & Dosage Matrix",
        "symptoms" to "Symptoms",
        "remedy" to "Remedy",
        "dosage" to "Dosage",
        "price" to "Market Price",
        "voice_active" to "Listening to voice...",
        "account_title" to "Your Account",
        "account_sub" to "Join the PlantGrid community",
        "sign_in" to "Sign In",
        "btn_agree" to "Agree & Continue",
        "exp_title" to "How is your experience?",
        "exp_sub" to "We would love to hear your suggestions.",
        "feedback" to "Give Feedback",
        "share_title" to "Let's grow smart together",
        "share_sub" to "Help other farmers by sharing the app.",
        "share_app" to "Share PlantGrid",
        "system_settings" to "System Settings",
        "mandi_title" to "Mandi Rates",
        "loc_perm_title" to "Allow Location Access",
        "loc_perm_sub" to "To see products available in your area, please allow location access.",
        "allow_loc" to "Allow Location",
        "org_fert" to "Organic Fertilizer",
        "reserve" to "Reserve",
        "comm_title" to "PlantGrid Community",
        "digi_ast" to "Digital Assistant",
        "cult_cycle" to "Cultivation Cycle",
        "exp_forum" to "Expert Forum",
        "fin_view" to "Financial Overview",
        "ask_crops" to "Ask about crops...",
        "ongoing" to "Ongoing",
        "earnings" to "Earnings Trend",
        "revenue" to "TOTAL REVENUE",
        "expenses" to "TOTAL EXPENSES",
        "crop_paddy" to "Paddy (Rice)",
        "crop_mango" to "Mango Orchard",
        "crop_potato" to "Potato Field",
        "crop_onion" to "Onion Plot",
        "crop_paddy_advice" to "Use Cartap for Paddy stem borer prevention.",
        "crop_mango_advice" to "Spray bio-fungicide for mango blossom protection.",
        "default_advice" to "All sectors are safe. Review NPK schedule.",
        "stem_borer_title" to "Stem Borer Anomaly",
        "stem_borer_symp" to "Drying stems and internal tissue damage.",
        "stem_borer_med" to "Cartap Hydrochloride 4G",
        "stem_borer_dose" to "7.5 kg per acre, soil application.",
        "leaf_blight_title" to "Bacterial Leaf Blight",
        "leaf_blight_symp" to "Yellowing leaf edges and drying patches.",
        "leaf_blight_med" to "Streptocycline + Copper Oxychloride",
        "leaf_blight_dose" to "Mix 6g + 500g in 200L water and spray.",
        "cult_roadmap" to "Your Cultivation Roadmap",
        "step1_title" to "Soil Setup & Testing",
        "step1_desc" to "Test soil pH and mix organic compost.",
        "step2_title" to "Seed Treatment & Sowing",
        "step2_desc" to "Use certified seeds and fungicide treatment.",
        "step3_title" to "Precision Irrigation (AWD)",
        "step3_desc" to "Maintain water levels as per sensor data.",
        "step4_title" to "Pest & Nutrition Management",
        "step4_desc" to "Timely NPK monitoring and remediation.",
        "init_title" to "Select Operational Mode",
        "init_sub" to "Choose how you want PlantGrid to optimize your farm",
        "mode_comm_title" to "Commercial High-Profit",
        "mode_comm_desc" to "Maximized market yield & satellite biomass tracking",
        "mode_organic_title" to "Eco-Organic Precision",
        "mode_organic_desc" to "Regenerative soil health & chemical-free growth",
        "mode_yield_title" to "High-Tech IoT Innovation",
        "mode_yield_desc" to "Maximum harvest per acre using IoT sensor fusion"
    )

    fun getString(key: String, lang: String): String {
        val dict = when (lang.lowercase()) {
            "or", "od", "odia" -> odia
            "hi", "hindi" -> hindi
            "pa", "punjabi" -> punjabi
            "ur", "urdu" -> urdu
            "te", "telugu" -> telugu
            "bn", "bengali" -> bengali
            else -> english
        }
        return dict[key] ?: english[key] ?: key
    }

    val stateLanguages = listOf(
        "en" to "English",
        "hi" to "हिन्दी (Hindi)",
        "or" to "ଓଡ଼ିଆ (Odia)",
        "te" to "తెలుగు (Telugu)",
        "bn" to "বাংলা (Bengali)",
        "ur" to "اردو (Urdu)",
        "pa" to "ਪੰਜਾਬੀ (Punjabi)"
    )
}
